### ISSUE TITLE
Add instructions to deploy to heroku

### ISSUE THREAD

**Issue by kbrock** [zamith/crystalshards#5]
Hi,

Could you update the readme to show how to post this app to heroku?
So others could just copy the recipe?

Thanks. This is very cool. thank you.

**Comment by zamith** [comment]
@kbrock I have written [this](https://subvisual.co/blog/posts/63-deploying-a-crystal-application-to-heroku), maybe it helps. I'd love a PR with that "recipe". ;)

**Comment by kbrock** [comment]
@zamith - thanks - on it
